#!/bin/sh

psql -d $POSTGRESQL_DATABASE -c "CREATE SCHEMA IF NOT EXISTS coffeeshop AUTHORIZATION $POSTGRESQL_USER;"
psql -d $POSTGRESQL_DATABASE -c "CREATE SCHEMA IF NOT EXISTS barista AUTHORIZATION $POSTGRESQL_USER;"
psql -d $POSTGRESQL_DATABASE -c "CREATE SCHEMA IF NOT EXISTS kitchen AUTHORIZATION $POSTGRESQL_USER;"
